export const movieListActions ={
    START_LOADING:"START_LOADING",
    END_LOADING:"END_LOADING",
    FETCH_MOVIES:"FETCH_MOVIES",
    FETCH_BY_SEARCH:"FETCH_BY_SEARCH",
    FETCH_CASTS:"FETCH_CASTS",
    FETCH_MOVIE_DETAILS:"FETCH_MOVIE_DETAILS",
    START_CAST_LOADING:"START_CAST_LOADING"
}